### ISSUE TITLE
Different maven dependencies to hadoop (0.20 vs. 2.5.0 vs. 2.6.0)

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-bigdata#13]
The version of Hadoop set in main maven pom.xml is

    <hadoop.version>2.6.0</hadoop.version>

but one of the dependencies, namely

    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-hadoop-pig</artifactId>
    <version>2.1.2.RELEASE</version>

requires

    <groupId>org.apache.hadoop</groupId>
    <artifactId>hadoop-yarn-common</artifactId>
    <version>2.6.0</version>
    <scope>compile</scope>

Even it's for the compile scope, there are two libs 2.5 and 2.6 on the classpath.

**Comment by reckart** [comment]
Btw. the "compile" scope is also the default if no scope is specified at all.

**Comment by habernal** [comment]
Only 2.6 version left; if any change of spring-data-hadoop-pig version in the future, this has to be addressed (not-managed dependencies)
