### ISSUE TITLE
Move Wikipages from Google Code

### ISSUE THREAD

**Issue by hpzorn** [dkpro/dkpro-bigdata#17]
The wiki pages/documentation on google code is no longer accessible, yet has not been moved to github.

**Comment by reckart** [comment]
I have "published" the project on Google Code again and made a note of transferring the information.

The way we typically do this now is creating a "xxx-doc" module in Maven where we place documentation in asciidoc format. This should then be maintained along with the code, can be built automatically by Jenkins and should be published along with the Java API docs when a release is made.

**Comment by reckart** [comment]
Wikipages migrated to asciidoc (except those with significant content).
Set "project moved" again on Google Code page.
Documentation built automatically on Jenknis and link is present in "Documentation" section of DKPro BigData website.
